Fail to solve eighth by changing sshUser
This is no surprise, as the activation script writes to the ~hello home
directory, which admin does not have permissions to.
Note the 'rm: cannot remove ...' line

$ SSH_ASKPASS_REQUIRE=prefer nix run . -- -s .#example.system
... completes fine
$ SSH_ASKPASS_REQUIRE=prefer nix run . -- -s .#example.hello
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[example.hello]
user = "hello"
ssh_user = "admin"
path = "/nix/store/jb6zazb4kml0zwqcli4kqxagbdz4q5cc-activatable-activate"
hostname = "localhost"
ssh_opts = ["-p", "2221", "-o", "UserKnownHostsFile=/dev/null", "-o", "StrictHostKeyChecking=no"]

🚀 ℹ️ [deploy] [INFO] Building profile `hello` for node `example`
🚀 ℹ️ [deploy] [INFO] Copying profile `hello` to node `example`
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of known hosts.
🚀 ℹ️ [deploy] [INFO] Activating profile `hello` for node `example`
🚀 ℹ️ [deploy] [INFO] Creating activation waiter
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of known hosts.
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of known hosts.
x11-ssh-askpass[542114]: Trying to grab keyboard ...
x11-ssh-askpass[542114]: Could not grab keyboard (someone else already has it)
⭐ ℹ️ [activate] [INFO] Activating profile
rm: cannot remove '/home/hello/.config/systemd/user/hello.service': No such file or directory
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
⭐ ⚠️ [activate] [WARN] De-activating due to error
error: no generation older than the current (1) exists
⭐ ❌ [activate] [ERROR] There was an error de-activating after an error was encountered: The rollback resulted in a bad exit code: Some(1)
🚀 ❌ [deploy] [ERROR] Activating over SSH resulted in a bad exit code: Some(1)
🚀 ℹ️ [deploy] [INFO] Revoking previous deploys