Issue six-point-five: just doing vmWithBootloader does not work
It runs out of disk space - the default disk size is pretty small, and
because of https://github.com/NixOS/nixpkgs/issues/128216 we don't share
the host's nix db, and so need to copy a lot more stuff than with 'vm'
(i.e. without bootloader)

$ nix run . -- .#example.system
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
warning: unknown flake output 'deploy'
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[example.system]
user = "root"
ssh_user = "admin"
path =
"/nix/store/4zlskwx7l82604wxdvhwylsg1cj226hs-activatable-nixos-system-example-nixos-system-21.11.20210606.d8eb97e"
hostname = "localhost"
ssh_opts = ["-p", "2221", "-o", "UserKnownHostsFile=/dev/null", "-o",
"StrictHostKeyChecking=no"]

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `example`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `example`
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of
known hosts.
(admin@localhost) Password:
[1/27/521 copied (18.4/393.3 MiB)] copying path
'/nix/store/77iwp66553657gnsmbx66y4gbpsmvpih-glibc-locales-2.32-46' to
'ssh://admin@localhost'error: preallocating file of 225226832 bytes: No
space left on device
error: writing to file: Broken pipe
🚀 ❌ [deploy] [ERROR] Failed to push profile: Nix copy command resulted
in a bad exit code: Some(1)