problem six-and-three-quarters: /boot gets unmounted
and then we complain we cannot write to /boot!

$ nix run . -- .#example.system
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
warning: unknown flake output 'deploy'
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[example.system]
user = "root"
ssh_user = "admin"
path =
"/nix/store/4zlskwx7l82604wxdvhwylsg1cj226hs-activatable-nixos-system-example-nixos-system-21.11.20210606.d8eb97e"
hostname = "localhost"
ssh_opts = ["-p", "2221", "-o", "UserKnownHostsFile=/dev/null", "-o",
"StrictHostKeyChecking=no"]

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `example`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `example`
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of
known hosts.
(admin@localhost) Password:
🚀 ℹ️ [deploy] [INFO] Activating profile `system` for node `example`
🚀 ℹ️ [deploy] [INFO] Creating activation waiter
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of
known hosts.
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of
known hosts.
(admin@localhost) Password:
👀 ℹ️ [wait] [INFO] Waiting for confirmation event...
123

ControlSocket /home/ben/.ssh/admin@localhost:2221 already exists,
disabling multiplexing
⭐ ℹ️ [activate] [INFO] Activating profile
123
stopping the following units: -.mount, boot.mount,
nix-.ro\x2dstore.mount, nix-.rw\x2dstore.mount, nscd.service,
systemd-udevd-control.socket, systemd-udevd-kernel.socket,
systemd-udevd.service, tmp-shared.mount, tmp-xchg.mount
Failed to stop -.mount: Job type stop is not applicable for unit
-.mount.
activating the configuration...
setting up /etc...
reloading user units for admin...
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: dhcpcd.service
starting the following units: -.mount, nscd.service,
systemd-udevd-control.socket, systemd-udevd-kernel.socket
the following new units were started: systemd-timesyncd.service,
time-sync.target
sed: can't read /boot/loader/loader.conf: No such file or directory
⭐ ⚠️ [activate] [WARN] De-activating due to error
error: no generation older than the current (1) exists
⭐ ❌ [activate] [ERROR] There was an error de-activating after an error
was encountered: The rollback resulted in a bad exit code: Some(1)
🚀 ❌ [deploy] [ERROR] Activating over SSH resulted in a bad exit code:
Some(1)
🚀 ℹ️ [deploy] [INFO] Revoking previous deploys