Fourth issue: lacking valid signature
$ nix run .
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
warning: unknown flake output 'deploy'
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[example.system]
user = "root"
ssh_user = "admin"
path =
"/nix/store/035x7wa0shql2nhbp0ls4fajcdha69v4-activatable-nixos-system-example-nixos-system-21.11.20210606.d8eb97e"
hostname = "localhost"
ssh_opts = ["-p", "2221", "-o", "UserKnownHostsFile=/dev/null", "-o",
"StrictHostKeyChecking=no"]

[example.hello]
user = "hello"
ssh_user = "hello"
path =
"/nix/store/jb6zazb4kml0zwqcli4kqxagbdz4q5cc-activatable-activate"
hostname = "localhost"
ssh_opts = ["-p", "2221", "-o", "UserKnownHostsFile=/dev/null", "-o",
"StrictHostKeyChecking=no"]

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `example`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `example`
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of
known hosts.
(admin@localhost) Password:
copying 36 pathserror: cannot add path
'/nix/store/0d7aqp53y96vv39dzhfgbgmmgd73md50-deploy-rs-0.1.0' because it
lacks a valid signature
[2/0/36 copied (2.1/12.4 MiB)] copying path
'/nix/store/2h0bdj0s29d3pgs10nghmyh65dz869y5-users-groups.json' to
'ssh://admin@localhost'Warning: Permanently added '[localhost]:2221'
(ED25519) to the list of known hosts.
(admin@localhost) Password:
[2/0/36 copied (1 failed) (2.1/12.4 MiB)] copying path
'/nix/store/2h0bdj0s29d3pgs10nghmyh65dz869y5-users-groups.json' to
'ssh://admin@localhost'Warning: Permanently added '[localhost]:2221'
(ED25519) to the list of known hosts.
(admin@localhost) Password: .1/12.4 MiB)] copying path
'/nix/store/54iig924q10ixiayfp3lvwqdsyk410an-nixos-system-example-nixos-system-21.11.20210606.d8eb97e-ac
[2/0/36 copied (1 failed) (2.1/12.4 MiB)] copying path
'/nix/store/54iig924q10ixiayfp3lvwqdsyk410an-nixos-system-example-nixos-system-21.11.20210606.d8eb97e-acerror:
cannot add path
'/nix/store/54iig924q10ixiayfp3lvwqdsyk410an-nixos-system-example-nixos-system-21.11.20210606.d8eb97e-activate-path'
because it lacks a valid signature
error (ignored): error: unexpected end-of-file
error: writing to file: Broken pipe
🚀 ❌ [deploy] [ERROR] Failed to push profile: Nix copy command resulted
in a bad exit code: Some(1)