Second error
We now see an error because the sshd key of the vm changes each time we
spin up a new vm.

$ nix run .
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
warning: unknown flake output 'deploy'
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
warning: Git tree '/home/ben/tmp/deploy-rs-upstream-example' is dirty
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[example.hello]
user = "hello"
ssh_user = "hello"
path =
"/nix/store/jb6zazb4kml0zwqcli4kqxagbdz4q5cc-activatable-activate"
hostname = "localhost"
ssh_opts = ["-p", "2221"]

[example.system]
user = "root"
ssh_user = "admin"
path =
"/nix/store/035x7wa0shql2nhbp0ls4fajcdha69v4-activatable-nixos-system-example-nixos-system-21.11.20210606.d8eb97e"
hostname = "localhost"
ssh_opts = ["-p", "2221"]

🚀 ℹ️ [deploy] [INFO] Building profile `hello` for node `example`
🚀 ℹ️ [deploy] [INFO] Copying profile `hello` to node `example`
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle
attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:BeXPzwKsfQPMZLdlbBh9sM67Kqdowe40o6vhyfF5Hz8.
Please contact your system administrator.
Add correct host key in /home/ben/.ssh/known_hosts to get rid of this
message.
Offending RSA key in /home/ben/.ssh/known_hosts:30
Host key for [localhost]:2221 has changed and you have requested strict
checking.
Host key verification failed.
error: cannot connect to 'hello@localhost'
🚀 ❌ [deploy] [ERROR] Failed to push profile: Nix copy command resulted
in a bad exit code: Some(1)