Eighth problem: 'hello' user is not trusted
This is basically the fourth issue again

$ SSH_ASKPASS_REQUIRE=prefer nix run . -- .#example.hello -s
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[example.hello]
user = "hello"
ssh_user = "hello"
path =
"/nix/store/jb6zazb4kml0zwqcli4kqxagbdz4q5cc-activatable-activate"
hostname = "localhost"
ssh_opts = ["-p", "2221", "-o", "UserKnownHostsFile=/dev/null", "-o",
"StrictHostKeyChecking=no"]

🚀 ℹ️ [deploy] [INFO] Building profile `hello` for node `example`
🚀 ℹ️ [deploy] [INFO] Copying profile `hello` to node `example`
Warning: Permanently added '[localhost]:2221' (ED25519) to the list of
known hosts.
copying 8 pathserror: cannot add path
'/nix/store/aq6mskwc56zmsfjq88als8vvk4llxy87-activate-activate-rs'
because it lacks a valid signature
error (ignored): error: unexpected end-of-file
error (ignored): error: writing to file: Broken pipe
error: unexpected end-of-file
🚀 ❌ [deploy] [ERROR] Failed to push profile: Nix copy command resulted
in a bad exit code: Some(1)